<?php 
ini_set('display_errors',1);  
error_reporting(E_ALL); 
?>
<!DOCTYPE html>
<html lang="en" dir="LTR">
<head>
	{{ partial("head") }}
	<meta name="description" content ="A temporary home for a pet is better than staying at a shelter, where supplies and human interaction are often limited">
	<title>Fostering - Information on fostering a pet</title>
</head>
<body id="b-resources">
	{{ partial("nav-main-mobile") }}
		{{ partial("nav-main") }}
		<header></header>
		<section id="content" class="layout">
			<h1>Fostering</h1>
			<hr/>
			<article class="content-paragraph">
				Fostering an animal is one of the most valuable services one  can provide in saving lives. Bottom line, animals in municipal shelters are always at risk of losing his/her life! And at any moment, for any number of reasons. There are a lot of concerns people have about fostering but like anything that’s worth doing, once you’ve conquered the “fear of the unknown,” it becomes easier to do again.
			</article>
			<article class="content-paragraph">
				Here is a video where Denise Herman, Head Dog Trainer and Founder of Empire of the Dog, gives us an overview of pet fostering:
			</article>
			<div class="video-container">
				<iframe width="560" height="315" src="https://www.youtube.com/embed/VIT0ZekvixY" frameborder="0" allowfullscreen></iframe>
			</div><!-- video-container -->
			<article class="content-paragraph">
				Here are some concerns outlined and debunked:
			</article>
			<article class="content-paragraph">
				1. <span class="underline"><em>"I will get attached."</span></em><br/><br/>
				How do you know?  Millions of Americans have fostered animals and didn’t end up keeping all of their fosters.  We understand the hesitation, but think of what you are doing as a service to even more animals than just one.  When you talk to your friends, family, colleagues you can mention what you are doing — this is spreading the rescue / adoption message in the best way possible — by word of mouth.
				<br/><br/>
				 In addition, your providing space for a homeless animal increases their chances of getting adopted because they’re in a home environment rather than a stressful cage/shelter environment.  Foster people can be involved in finding a new home for their foster pet or not — there’s no obligation to be the one to find the animal a new home.  However, if you’d like to be involved by making flyers, posting pictures with a description on Craigslist with the rescue groups website URL, that’s great!  Your testimony about your foster cat or dog is immensely powerful in finding him or her a forever home.
				 <br/><br/>
				When that animal gets adopted, you can foster another animal and giving him or her the same chance, especially an animal that needs extra love.
				Most importantly, if you want to try it out but have some fears, tell the rescue group you’re talking to or contact us and we can provide contacts to help you get started with your questions or to just jump right in and foster. We will also provide foster tips here from one of NYC’s well known trainers.
			</article>
			<br/>
			<article class="content-paragraph">
				2. <span class="underline"><em>"Isn’t that cruel to give them your home then move them to another home?"</em></span><br/><br/>
				Your temporary home for a shelter animal or one that’s been rescued from the street or given up will allow him or her to put their best foot forward for potential adopters.  With animals, like wiht humans, an adoption match is one filled with love, and when a cat or dog is placed in a new, loving home, you’ll see how well they adjust, because all they needed was love in the first place.
			</article>
			<br/>
			<article class="content-paragraph">
				3. <span class="underline">"They won’t get adopted if they’re in my home."</span></em><br/><br/>
				If you  haven’t heard of <a href="http://petfinder.com" class="link-regular" target="_blank">petfinder.com</a>, <a href="http://petango.com" class="link-regular" target="_blank">petango.com</a>, <a href="http://adoptapet.com" class="link-regular" target="_blank">adoptapet.com</a>, among many other adoption website, then welcome to one of the primary resources for rescuers to find new, loving homes for their rescued animals.  Animals in foster homes get tons of exposure online, with photos, video, and lovely descriptions in their posting.
				<br/><br/>
				 In addition, most rescue groups have adoption events either once in a while or on a steady schedule at a pet supplies store like Petco or PetSmart.  Foster parents can bring their adoptables to these events to meet people that might’ve already spotted them online or who just want to meet a potential new pet for the first time.
				 <br/><br/>
				The more pets there are available for adoption online, the better the rescue community is able to steer people clear of pet shops and breeders — which helps all of us toward our goal of eliminating animal homelessness.  So whether a pet is in a shelter or a foster home, these online resources are a primary way animals find new homes.
			</article>
			<br/>
			<article class="content-paragraph">Open your heart and your home to a foster today, and save a life!</article>
		</section><!-- #content layout -->
	{{ partial("footer-main") }}
</body>
</html>