<?php 
ini_set('display_errors',1);  
error_reporting(E_ALL); 
?>
<!DOCTYPE html>
<html lang="en" dir="LTR">
<head>
	{{ partial("head") }}
	<meta name="description" content ="404 Error Not Found">
	<title>404 Error - Not Found</title>
</head>
<body>
	<section class="layout error-container">
		<div class="error-img">
			<img src="http://afarnyc.org/img/photos/lab-puppy.jpg" alt="403 Error" class="error-display">
		</div>
		<div class="error-message">
			<p class="error-title">Oops!</p>
			<p>
				The page you are looking for either does not exist or has moved, but this pup is here for you! Come back before this puppy gets anxious and starts chewing your wires, shoes, phone...
			</p>
			<a href="/" class="cta-ghost">Return Home</a>
		</div>
	</section><!-- layout -->
</body>
</html>