<nav id="nav-fixed" class="nav-main">
	<section class="layout">
		<ul>
		  <li><a href="/" class="nav-logo">afar</a></li>
      <li class="a-whatwedo">{{ link_to("whatwedo", "What We Do") }}</li>
      <li class="a-about">{{ link_to("about", "About") }}</li>
      <li class="a-programs">{{ link_to("programs", "Programs") }}</li>
      <li class="a-resources">{{ link_to("resources", "Resources") }}</li>
      <li><a href="http://blog.afarnyc.org">Blog</a></li>
      <li class="a-volunteer">{{ link_to("volunteer", "Volunteer") }}</li>
      <li class="a-donate">{{ link_to("donate", "Donate") }}</li>
      <li class="a-contact">{{ link_to("contact", "Contact") }}</li>
    </ul>
  </section><!-- layout -->
</nav><!-- main-nav -->