<nav id="nav-home" class="nav-main">
	<section class="layout">
		<ul>
		  <li id="li-first"><a href="/" class="nav-logo">afar</a></li>
      <li>{{ link_to("whatwedo", "What We Do") }}</li>
      <li>{{ link_to("about", "About") }}</li>
      <li>{{ link_to("programs", "Programs") }}</li>
      <li>{{ link_to("resources", "Resources") }}</li>
      <li><a href="http://blog.afarnyc.org">Blog</a></li>
      <li>{{ link_to("volunteer", "Volunteer") }}</li>
      <li>{{ link_to("donate", "Donate") }}</li>
      <li>{{ link_to("contact", "Contact") }}</li>
    </ul>
  </section><!-- layout -->
</nav><!-- main-nav -->