<?php 
ini_set('display_errors',1);  
error_reporting(E_ALL); 
?>
<!DOCTYPE html>
<html lang="en" dir="LTR">
<head>
	{{ partial("head") }}
	<meta name="description" content ="Updates on animal rights policies in the U.S. and across the world">
	<title>Legislation - Current legal news on animal welfare</title>
</head>
<body id="b-resources">
	{{ partial("nav-main-mobile") }}
		{{ partial("nav-main") }}
		<header></header>
		<section id="content" class="layout">
			<h1>Legislation</h1>
			<hr/>
			<article class="content-paragraph">
				Real change for animal rights policies, at a legislative level, are the result of tireless advocacy. Here is the current news such activism has brought about:
			</article>
		</section><!-- #content layout -->
		<section class="layout" id="content-0">
		<a href="http://www.nytimes.com/2015/05/15/nyregion/a-new-york-state-senate-bill-is-a-win-for-four-legged-guests-in-outdoor-restaurants.html?smid=fb-nytimes&amp;smtyp=cur&amp;bicmp=AD&amp;bicmlukp=WT.mc_id&amp;bicmst=1409232722000&amp;bicmet=1419773522000&amp;_r=1" target="_blank">
				<div class="blurb blurb-first">
					<div class="blurb-header">
						<div class="blurb-title">New York State Senate Bill Is a Win for Four-Legged Guests in Outdoor Restaurants</div>
						<div class="blurb-date">05&#8226;15&#8226;15</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						A brush of terrier fur against a patron’s open toes as she sips her morning coffee. A nudge from a rangy German shepherd beneath an outdoor table piled high with croissants. Paws scraping against the sidewalk in pursuit of dropped bits of omelet. Until now, New York State health law has sought to...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="http://www.animalequality.net/node/703" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">New Zealand Legally Recognises Animals as 'Sentient' Beings</div>
						<div class="blurb-date">05&#8226;12&#8226;15</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						An ammendment to New Zealand law on behalf of the The Animal Welfare Amendment Bill, which was passed on Tuesday, states that animals, like humans, are "sentient" beings. "To say that animals are sentient is to state explicitly that they can experience both positive and...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="http://www.nysenate.gov/press-release/new-york-senate-passes-ball-s-bill-create-registry-convicted-animal-abusers" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">NY Senate Passes Bill to Create Animal Abuse Registry</div>
						<div class="blurb-date">08&#8226;01&#8226;13</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						Senator Greg Ball announced that the New York State Senate has passed S2305A, legislation that will require those that violate Buster’s Law by abusing animals, register his or her name and address with the division of criminal justice services, undergo a psychiatric...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="http://stopbsl.org/2013/07/03/rhode-island-hb5671-the-bill-to-outlaw-breed-discrimination-passes-full-senate/" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">Rhode Island Passes Bill to Outlaw Breed Discrimination</div>
						<div class="blurb-date">07&#8226;03&#8226;13</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						Rhode Island HB5671 was passed by the full Senate today with a vote of 21-6. The bill has moved along very quickly after an initial stall out of the gate.  Introduced in late February, the bill was held for study by the House committee.  The House committee passed the bill on June 20th and...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="http://stopbsl.org/2013/06/05/connecticut-governor-signs-hb6311-outlawing-breed-discrimination/?utm_source=feedburner&amp;utm_medium=email&amp;utm_campaign=Feed%3A+StopBsl+%28Stop+BSL%29" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">Connecticut Governor Signs HB6311 Outlawing Breed Discrimination</div>
						<div class="blurb-date">06&#8226;05&#8226;13</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						Connecticut HB 6311 has been signed into law by the Governor and now becomes the 15th state to outlaw breed discrimination. Like the recently passed Nevada Assembly Bill 110, Connecticut HB6311 has no home rule exemption or grandfather clause...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="http://www.huffingtonpost.com/2013/05/29/nevada-bans-dog-breed-discrimination_n_3356032.html" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">Nevada 14th State to Ban Breed Discrimination Against Pitbulls</div>
						<div class="blurb-date">05&#8226;30&#8226;13</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						Governor Brian Sandoval recently signed a bill that will prevent local governments from passing legislation that deems dogs dangerous based solely on their breed. Breed specific legislation, or BSL, allows cities around the country to seize and kill dogs simply because they appear to belong to a "dangerous breed"...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
			<a href="https://malegislature.gov/Bills/188/Senate/S969" target="_blank">
				<div class="blurb">
					<div class="blurb-header">
						<div class="blurb-title">Massachusetts Politicians Aim to Undermine New Breed Law</div>
						<div class="blurb-date">05&#8226;25&#8226;13</div>
					</div><!-- blurb-header -->
					<div class="blurb-text">
						Last year, Massachusetts passed a comprehensive public safety bill and became the 13th state in the nation to outlaw breed discrimination. Now, politicians are trying to persuade the state legislature to undermine the new law and allow towns to ban any breed of dog...
					</div><!-- blurb-text -->
				</div><!-- blurb -->
			</a>
		</section><!-- #content-0 layout -->
	{{ partial("footer-main") }}
</body>
</html>