<?php 
ini_set('display_errors',1);  
error_reporting(E_ALL); 
?>
<!DOCTYPE html>
<html lang="en" dir="LTR">
<head>
	{{ partial("head") }}
	<meta name="description" content ="Volunteers are at the core of our organization: the various talents that are applied to our efforts makes our goals attainable. Get involved!">
	<title>Volunteer - Help us out in what you do best</title>
</head>
<body id="b-volunteer">
	{{ partial("nav-main-mobile") }}
		{{ partial("nav-main") }}
		<header></header>
		<section id="content" class="layout">
			<h1>Volunteer</h1>
			<hr/>
			<article class="content-paragraph">
				Volunteers are at the core of our organization. If you want to make a difference in how our animals are treated, get involved with us. 
			</article>
			<article class="content-paragraph">
				Even if you don't fall into one of the listed categories, we could still use your help in whatever useful skill you can contribute. Also, <em>you don't have to live in NYC to help</em>--most our volunteers work remotely from areas like CA, DC, VA, IL, etc.
			</article>
			<article class="content-paragraph">
				We give every dedicated volunteer AFAR gear and goodies and can offer our 
				extensive network to aid in your career goals. There is merit in becoming 
				a part of the AFAR family so find out how you can help.
			</article>
			<a href="/contact" class="cta-ghost lg-width">Volunteer with Us</a>
		</section>

		<section class="layout mar-auto" id="content-0">
			<div class="content-left-50 no-padding">
				<ul class="volunteer">
					<li>Bloggers
						<ul class="nested-list">
							<li><em>Responsibilities</em>: produce, at minimum, biweekly blog posts about animal welfare and related topics for our blog, of your choice</li>
						</ul>
					</li>
					<li>Editors
						<ul class="nested-list">
							<li><em>Responsibilites</em>: review all written submissions, draft 
							grant proposals, and check for correctness as well as oversee 
							all written content across our social media, site, and blog</li>
						</ul>
					</li>
					<li>Marketing Analysts
						<ul class="nested-list">
							<li><em>Responsibilites</em>: create and implement our social media campaigns, outreach strategies, and conduct small research into how they 
							can be improved--in the scope of AFAR's mission</li>
						</ul>
					</li>
					<li>User Experience / Interface Designers 
						<ul class="nested-list">
							<li><em>Responsibilites</em>: creating iterations of our current web interface, using software such as Baslmiq, Axure, Adobe Creative Suite, and conduct small user research (must have some web design / UX / UI experience, but a strong willingness to learn is also acceptable)</li>
						</ul>
					</li>
					<li>Front-end Developers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: revamp AFAR's technology efforts (website, blog, SM, etc.) using Node.js, jQuery, JavaScript, HTML, CSS and Sass (must have some knowlede of web technologies or at least a strong willingness to learn)</li>
						</ul>
					</li>
					<li>Back-end Developers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: in charge of updating our database structures, maintaining server, and adding to our CMS using Ubuntu, SQL, NoSQL, Python, Node.js (must be a in software engineering industry, Computer Science student, or show proficiency in server side scripting, database management, and web development across all layers)</li>
						</ul>
					</li>
					<li>Publishers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: seasoned or newcomer in the publishing
							industry with exposure to corporate branding, slogan creation, and 
							content revision</li>
						</ul>
					</li>
					<li>Videographers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: experienced production / video 
							specialist with equipment and proficiency in modern video editing software such as After Effects, Final Cut Pro, etc. (preferable 
							local or near NYC, but remote is acceptable)</li>
						</ul>
					</li>
					<li>Photographers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: experienced photographer with 
							equipment and proficiency in modern photo editing (preferable 
							local or near NYC, but remote is acceptable)</li>
						</ul>
					</li>
					<li>Graphic Designers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: experienced graphic designer / 
							artist with proficiency in Adobe Illustrator, Photoshop, 
							Indesign and / or other modern rendering software along with
							exposure / experience in logo ideation, branding, and billboard
							marketing (not required but definitely favorable)</li>
						</ul>
					</li>
					<li>Event / Program Managers
						<ul class="nested-list">
							<li><em>Responsibilites</em>: seasoned event / program manager 
							with experience in fundraising and non-profit events (must show 
							proficient social ability and a willingness to learn 
							non-profit event management)</li>
						</ul>
					</li>
				</ul><!-- volunteer -->
			</div><!-- content-left-50 -->

			<div class="content-right-50 no-padding">
				<div class="img-circle-200 circle-350 volunteer-pic"></div>
			</div><!-- content-right-50 -->
		</section><!-- #content-0 layout -->
		<br/><br/>
	{{ partial("footer-main") }}
</body>
</html>